== Gson integration

A `JsonSerializer` and a `JsonDeserializer` are provided to configure link:holon-core.html#PropertyBox[PropertyBox] serialization to _JSON_ format and deserialization from _JSON_ format.

=== Configuration and use

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.json</groupId>
<artifactId>holon-gson</artifactId>
<version>{revnumber}</version>
----

To enable `PropertyBox` handling in Gson, registering the suitable `JsonSerializer` and a `JsonDeserializer` pair, the link:{apidir}/com/holonplatform/json/gson/GsonConfiguration.html[GsonConfiguration^] utility interface can be used:

[source, java]
----
include::{examplesdir}/com/holonplatform/json/examples/ExampleGson.java[tag=configuration,indent=0]
----
<1> Get a pre-configured `GsonBuilder` with `PropertyBox` support
<2> Get a previously available `GsonBuilder`
<3> Configure the builder for `PropertyBox` support

With a properly configured `Gson` instance, a `PropertyBox` can be serialized and deserialized just like any another object. As described in the <<PropertyBox>> section, you need to declare the `PropertySet` to use as a _Context_ resource at `PropertyBox` deserialization time.

[source, java]
----
include::{examplesdir}/com/holonplatform/json/examples/ExampleGson.java[tag=serdeser,indent=0]
----
<1> Obtain a pre-configured `Gson` instance
<2> Build a `PropertyBox` using `PROPERTY_SET` as property set
<3> Serialize the `PropertyBox` to JSON. 
<4> Deserialize back the JSON definition to a `PropertyBox` instance using `PROPERTY_SET` as property set, declaring it as thread-bound _Context_ resource through the `execute(...)` method

In the example above, the `PropertyBox` instance will be serialized as a JSON object like this:

[source, json]
----
{
  "id": 1,
  "description": "Test"
}
----

=== Gson `java.time.*` data types support

The Java 8 date and time API data types serialization and deserialization are supported out-of-the-box when using a `GsonBuilder` obtained or configured through the link:{apidir}/com/holonplatform/json/gson/GsonConfiguration.html[GsonConfiguration^] interface methods.

Supported `java.time.*` data types are: `LocalDate`, `LocalTime`, `LocalDateTime`, `OffsetTime`, `OffsetDateTime`, `ZonedDateTime` and `Instant`.

This way, you can deal transparently with the `java.time.*` serialization and deserialization without the need for further configurations.

Example of a `LocalDate` object serialization and deserialization:

[source, java]
----
include::{examplesdir}/com/holonplatform/json/examples/ExampleGson.java[tag=temporals,indent=0]
----
<1> Use a properly configured `Gson` instance
<2> Serialize given `LocalDate` in JSON. This will result in `"2018-01-05"`
<3> Deserialize back the JSON date into a `LocalDate`

=== ISO-8601 `java.util.Date` serialization

When using a Gson `GsonBuilder` obtained or configured through the link:{apidir}/com/holonplatform/json/gson/GsonConfiguration.html[GsonConfiguration^] methods, the serialization of `java.util.Date` data types using the *ISO-8601* format is enabled by default, to provide a standard and more readable way to represent date and time types in the serialized JSON output.

So a `java.util.Date` type value is serialized with the following pattern:

----
2018-01-05T10:30:25
----

NOTE: The timezone offset is included if available.

Since a `java.util.Date` always contains all the date and time parts, the value is serialized including the time part by default.

If the `java.util.Date` value is serialized as a `Property` value within a `PropertyBox`, the `PropertyConfiguration` is checked to obtain the `TemporalType` of the property. If available, the `java.util.Date` value is serialized according to the property temporal type, i.e. as a `DATE` (only the date part), as a `TIME` (only the time part) or as a `DATE_TIME` (both the date and the time part).

TIP: See the link:holon-core.html#PropertyConfiguration[PropertyConfiguration] documentation for further information.

When the `java.util.Date` value is not bound to a `Property`, you can use a `ThreadLocal` variable to set the current `TemporalType` which has to be used to serialize the date/time value. The value serialization temporal type can be setted and cleared using the `setCurrentTemporalType(TemporalType temporalType)` and `removeCurrentTemporalType()` methods of the link:{apidir}/com/holonplatform/json/datetime/CurrentSerializationTemporalType.html[CurrentSerializationTemporalType^] class. 

[source, java]
----
include::{examplesdir}/com/holonplatform/json/examples/ExampleGson.java[tag=ttype,indent=0]
----
<1> Use a properly configured `Gson` instance
<2> Set the current `TemporalType` to `DATE`
<3> Only the date part will be serialized in JSON: `"2018-01-05"`
<4> Clear the current `TemporalType`

=== JAX-RS integration

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.json</groupId>
<artifactId>holon-gson-jaxrs</artifactId>
<version>{revnumber}</version>
----

A set of JAX-RS extension classes are provided to configure `PropertyBox` JSON support in JAX-RS using _Gson_, and in a more general sense, to configure _Gson_ as main serializer/deserializer in a JAX-RS server and/or client for the JSON media type.

The JAX-RS _Gson_ extensions relies on standard `ContextResolver` type to provide the `Gson` instance to use to perform JSON serialization and deserialization. This `Gson` instance must be configured with `PropertyBox` support as described above to handle `PropertyBox` types consistently.

To setup _Gson_ as provider for JSON message type handling, the link:{apidir}/com/holonplatform/json/gson/jaxrs/GsonFeature.html[GsonFeature^] JAX-RS `Feature` can be registered in the JAX-RS application.

If you use link:https://github.com/jersey[Jersey^] or link:http://resteasy.jboss.org[Resteasy^] as JAX-RS implementation, there is no need to explicitly register the `GsonFeature`, just ensure the `holon-gson` jar is in classpath and the _Gson_ support will be configured automatically, leveraging Jersey _AutoDiscoverable_ and Resteasy Java Service extensions features.

==== `PropertyBox` deserialization

When a `PropertyBox` is used as a JAX-RS resource method *parameter* (for methods which declare to consume  `application/json` media type), the JSON deserialization of the input into a `PropertyBox` instance needs to know the `PropertySet` to use in order to create the property box. For this purpose, the `@PropertySetRef` annotation can be used at method parameter level to declare the `PropertySet` instance to use to deserialize the property box.

The link:../api/holon-core/com/holonplatform/core/property/PropertySetRef.html[PropertySetRef^] annotation allows to declare the `PropertySet` instance as the `public static` *field* of a given class, which must be specified in the `value()` annotation attribute. If more than one `public static` field of `PropertySet` type is present in declared class, the `field()` annotation attribute can be used to specify the right field name.

[source, java]
----
include::{examplesdir}/com/holonplatform/json/examples/ExampleGson.java[tag=jaxrs,indent=0]
----
<1> Create a JAX-RS `Client`
<2> Perform a `PUT` request providing a `PropertyBox` value as JSON. At the endpoint resource level, the `PropertyBox` type input parameter of the `serialize` method is annotated with `@PropertySetRef` in order  to declare the property set to use to deserialize the property box from JSON
<3> Perform a `GET` request for a JSON serialized `PropertyBox` value, providing the `PropertySet` to use for deserialization as a `Context` thread-bound resource

==== JAX-RS integration configuration

The following configuration properties are available to tune or disable the JAX-RS integration features for _Gson_ and `PropertyBox` support:

* `holon.gson.disable-resolver`: If this property is present in JAX-RS application properties, the Gson *ContextResolver* auto-configuration is disabled
* `holon.gson.disable-autoconfig`: If this property is present in JAX-RS application properties, all the Gson and `PropertyBox` JSON serialization/deserialization features will be disabled
* `holon.jaxrs.json.pretty-print`: If `true`, enables _pretty printing_ of serialized JSON

[[GsonJson]]
=== Gson `Json` API implementation

Gson can be used as <<JsonAPI>> implementation.

When the `holon-gson` artifact is present in classpath, a suitable `JsonProvider` is automatically registered, and the `Json` API implementation can be obtained through the `Json.get()` and `Json.require()` methods.

Otherwise, the Gson `Json` API implementation can be directly obtained using the link:{apidir}/com/holonplatform/json/gson/GsonJson.html[GsonJson^] interface, through one of the `create()` methods.

[source, java]
----
include::{examplesdir}/com/holonplatform/json/examples/ExampleGson.java[tag=json,indent=0]
----
<1> Get the Gson `Json` API implementation using the registered provider
<2> Obtain the Gson `Json` API implementation directly

=== Spring integration

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.json</groupId>
<artifactId>holon-gson-spring</artifactId>
<version>{revnumber}</version>
----

The link:{apidir}/com/holonplatform/json/gson/spring/SpringGsonConfiguration.html[SpringGsonConfiguration^] utility class can be used to configure a Spring `RestTemplate`, ensuring that a `GsonHttpMessageConverter` is registered and bound to a `Gson` instance correctly configured for `PropertyBox` JSON serialization/deserialization.

[source, java]
----
include::{examplesdir}/com/holonplatform/json/examples/ExampleGson.java[tag=spring,indent=0]
----
<1> Configure the `RestTemplate`

=== Spring Boot integration

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.json</groupId>
<artifactId>holon-gson-spring</artifactId>
<version>{revnumber}</version>
----

The `GsonAutoConfiguration` Spring Boot _auto-configuration_ class is provided to automatically configure a `Gson` instance *singleton bean*, correctly configured for `PropertyBox` JSON serialization/deserialization. 

This way, the `RestTemplate` instances obtained through the `RestTemplateBuilder` Spring Boot builder will be automatically pre-configured with a `Gson` message converter with `PropertyBox` support.

IMPORTANT: The `Gson` auto-configuration is triggered only if a `Gson` type bean is not already registered in Spring context.

To disable this auto-configuration feature the `GsonAutoConfiguration` class can be excluded:

[source, java]
----
@EnableAutoConfiguration(exclude={GsonAutoConfiguration.class})
----
