= Holon JSON support
:revnumber: {project-version}
:apidir: ../api/holon-json
:linkattrs:
:sectnums:
:nofooter:
:toc: left
:toclevels: 3

Copyright © 2016-2017

_Copies of this document may be made for your own use and for distribution to others, provided that you do not charge any fee for such copies and further provided that each copy contains this Copyright Notice, whether distributed in print or electronically._

== Introduction

The Holon Platform *JSON* module provides integration support between the platform foundation link:holon-core.html#PropertyBox[PropertyBox] data structure and the most popular _JSON_ processing libraries:

* link:https://github.com/google/gson[Gson]
* link:http://wiki.fasterxml.com/JacksonHome[Jackson]

The module faces the following integration concerns:

* _Gson_ *GsonBuilder* configuration
* _Jackson_ *ObjectMapper* configuration
* Full support of the *Java 8 date and time API* for the `java.time.*` data types serialization and deserialization
* *JAX-RS* integration and auto-configuration
* _Spring_ *RestTemplate* configuration
* *Spring boot* auto-configuration 

== Obtaining the artifacts

The Holon Platform uses https://maven.apache.org[Maven^] for projects build and configuration. All the platform artifacts are published in the *Maven Central Repository*, so there is no need to explicitly declare additional repositories in your project `pom` file.

At the top of each _section_ of this documentation you will find the Maven _coordinates_ (group id, artifact id and version) to obtain the artifact(s) as a dependency for your project.

A *BOM (Bill Of Materials)* `pom` is provided to import the available dependencies for a specific version in your projects. The Maven coordinates for the core BOM are the following:

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.json</groupId>
<artifactId>holon-json-bom</artifactId>
<version>{revnumber}</version>
----

The BOM can be imported in a Maven project in the following way:

[source, xml, subs="verbatim,quotes,attributes+"]
----
<dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>com.holon-platform.json</groupId>
			<artifactId>holon-json-bom</artifactId>
			<version>{revnumber}</version>
			*<type>pom</type>*
			*<scope>import</scope>*
		</dependency>
	</dependencies>
</dependencyManagement>
----

=== Using the Platform BOM

The Holon Platform provides an *overall Maven BOM (Bill of Materials)* to easily obtain all the available platform artifacts.

See link:index.html#obtain-the-platform-artifacts[Obtain the platform artifacts] for details.

[[JsonPropertySet]]
== Dealing with properties and `PropertySet`

A link:holon-core.html#PropertyBox[PropertyBox] is a versatile and general-purpose data container object which uses link:holon-core.html#Property[Property] type keys as reference for the data it manages.

The *Properties* to which data are bound, i.e. the `PropertySet` associated with the `PropertyBox`, are complex and extensible objects, highly customizable by the developer. For this reason, a `Property` is *never serialized in JSON* by this module. 

=== Serialization

Only `Path` properties are serialized into _JSON_, using the path *name* as property name of the produced _JSON object_ and _JSON_ data type consistent with the property type.

This way, the _JSON_ definitions produced by the serialization of a `PropertyBox` are fully analogous to a standard _JSON_ *object*, composed by a list of property _names_ associated to a _value_ of a suitable type, which can be eventually deserialized in a generic data object (with a consistent internal structure) even a language different from Java.  

=== Deserialization

To deserialize a _JSON object_ into a `PropertyBox` instance, the `PropertySet` to use for the `PropertyBox` is required and must be available as a link:holon-core.html#Context[Context] resource (typically thread-bound).

To bound a `PropertySet` instance to the default thread-scoped resource set of the Holon Platform _Context_, the `execute(Callable operation)` method can be used.

See the next sections for further details and use-case examples.

== Date and time data types

=== `java.time.*` data types support

The support for the Java 8 date and time API data types is enabled out-of-the-box, and allows to deal transparently with the temporal data types such as `LocalDate`, `LocalTime` and `LocalDateTime`.

This includes any temporal date type used with a `Property` and accordingly any `java.time.*` data type serialized and deserialized within a `PropertyBox`.

See the next sections for further details according to the specific available implementations.

=== `java.util.Date` serialization and deserialization

By default, the `java.util.Date` data types are serialized in JSON using the *ISO-8601* format, to provide a standard and more readable way to represent date and time types in the serialized JSON output.

See the next sections for further details according to the specific available implementations.

// Inclusions

include::_gson.adoc[]

include::_jackson.adoc[]

== Loggers

By default, the Holon platform uses the https://www.slf4j.org[SLF4J^] API for logging. The use of SLF4J is optional: it is enabled when the presence of SLF4J is detected in the classpath. Otherwise, logging will fall back to JUL (`java.util.logging`).

The logger names for the *JSON* module are:

* `com.holonplatform.json.gson` for the _Gson_ integration classes
* `com.holonplatform.json.jackson` for the _Jackson_ integration classes

== System requirements

=== Java

The Holon Platform JSON module requires https://www.java.com[Java] *8* or higher.
